// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCJ15qGIuYyADhD-tPwqx7ycGWuxzWYM',
    appId: '1:889271788639:web:b71350318925684730a7ea',
    messagingSenderId: '889271788639',
    projectId: 'sos-flutter-f0e44',
    authDomain: 'sos-flutter-f0e44.firebaseapp.com',
    storageBucket: 'sos-flutter-f0e44.firebasestorage.app',
    measurementId: 'G-79K00NPMWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB12K1AtNO8Sy5xFZy0CGAiKQwScdjoXI',
    appId: '1:889271788639:android:4d45b2dd3fed5ee230a7ea',
    messagingSenderId: '889271788639',
    projectId: 'sos-flutter-f0e44',
    storageBucket: 'sos-flutter-f0e44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm4ygglv3znhQH736JJXrs54s4xZIpQ98',
    appId: '1:889271788639:ios:07a2ba4e4117215530a7ea',
    messagingSenderId: '889271788639',
    projectId: 'sos-flutter-f0e44',
    storageBucket: 'sos-flutter-f0e44.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm4ygglv3znhQH736JJXrs54s4xZIpQ98',
    appId: '1:889271788639:ios:07a2ba4e4117215530a7ea',
    messagingSenderId: '889271788639',
    projectId: 'sos-flutter-f0e44',
    storageBucket: 'sos-flutter-f0e44.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABCJ15qGIuYyADhD-tPwqx7ycGWuxzWYM',
    appId: '1:889271788639:web:bb8f6cdd89b258e830a7ea',
    messagingSenderId: '889271788639',
    projectId: 'sos-flutter-f0e44',
    authDomain: 'sos-flutter-f0e44.firebaseapp.com',
    storageBucket: 'sos-flutter-f0e44.firebasestorage.app',
    measurementId: 'G-X78FF2XFN7',
  );
}
